# Generated by Django 3.2.5 on 2021-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
