# Generated by Django 3.2.5 on 2021-12-01 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0002_patientuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='bloodgroup',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('dob', models.DateField()),
                ('image', models.FileField(null=True, upload_to='')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('specialization', models.CharField(max_length=30, null=True)),
                ('remarks', models.CharField(max_length=60, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
