# Generated by Django 3.2.5 on 2021-12-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='applydate',
            new_name='appointmentdate',
        ),
    ]
