# Generated by Django 3.2.5 on 2021-12-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20211201_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user',
            new_name='patient',
        ),
    ]
