# Generated by Django 3.2.5 on 2021-12-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_rename_user_feedback_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.patientuser'),
        ),
    ]
